canvas = document.getElementById("MC");
CTX = canvas.getContext("2d");
color = "red";
CTX.beginPath();
CTX.strokeStyle = "blue";
CTX.lineWidth = 2;
CTX.arc(200,200,40,0, 2* Math.PI);
CTX.stroke();
CTX.beginPath();
CTX.strokeStyle = "black";
CTX.lineWidth = 2;
CTX.arc(300,200,40,0, 2* Math.PI);
CTX.stroke();
CTX.beginPath();
CTX.strokeStyle = "yellow";
CTX.lineWidth = 2;
CTX.arc(250,250,40,0, 2* Math.PI);
CTX.stroke();
CTX.beginPath();
CTX.strokeStyle = "red";
CTX.lineWidth = 2;
CTX.arc(400,200,40,0, 2* Math.PI);
CTX.stroke();
CTX.beginPath();
CTX.strokeStyle = "green";
CTX.lineWidth = 2;
CTX.arc(350,250,40,0, 2* Math.PI);
CTX.stroke();